import { Inter } from "next/font/google";

import "./globals.css";
import LeftNav from "./src/components/LeftNav";
import MobileNav from "./src/components/MobileNav";
import TopBar from "./src/components/TopBar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dua & Ruqyah | All Duas Collection",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-[#ebeef2] p-0  2xl:p-9 2xl:pb-0 pb-0  flex gap-x-5 h-full overflow-hidden">
          {/* left nav - desktop - hidden on mobile */}
          <div className="hidden 2xl:block w-[100px] bg-white px-4 py-8 rounded-xl overflow-y-auto h-[91vh]">
            <LeftNav />
          </div>

          <div className="w-full h-full overflow-hidden">
            <TopBar />
            {/* bottom nav - mobile - hidden on desktop */}
            <MobileNav />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
