export const actions = {
  duas: {
    SET_DUA: "SET_DUA",
  },
  categories: {
    FETCH_CATEGORY_REQUEST: "FETCH_DATA",
    FETCH_CATEGORY_SUCCESS: "FETCH_CATEGORY_SUCCESS",
    FETCH_CATEGORY_FAILURE: "FETCH_CATEGORY_FAILURE",
    FETCH_SUB_CATEGORY_SUCCESS: "FETCH_SUB_CATEGORY_SUCCESS",
    FETCH_SUB_CATEGORY_FAILURE: "FETCH_SUB_CATEGORY_FAILURE",
  },
};
